from __future__ import annotations

"""Facade module preserving the historic bridge contract API.

The public surface stays stable for all current import sites, while the
implementation is now decomposed into focused submodules covering versions,
capabilities, runtime parameters, command policy, and envelope validation.
"""

from robot_contracts.capabilities import (
    BRIDGE_CAPABILITIES,
    COMMAND_ACK_STATUSES,
    COMMAND_LIFECYCLE_STATUSES,
    COMMAND_TYPES,
    COMPATIBILITY_ACK_STATUS_BY_LIFECYCLE,
    INBOUND_EVENT_TYPES,
    TERMINAL_COMMAND_ACK_STATUSES,
    TERMINAL_COMMAND_LIFECYCLE_STATUSES,
    TRANSPORT_SUMMARY_KEYS,
    compatibility_ack_status,
    supported_capabilities,
)
from robot_contracts.command_policy import (
    COMMAND_PERMISSION_MATRIX,
    COMMAND_TARGET_MODE,
    MODE_TRANSITION_TARGETS,
    CommandContext,
    ContractCheckResult,
    allowed_target_modes,
    command_allowed_modes,
    command_capability_snapshot,
    command_guard,
    mode_transition_allowed,
)
from robot_contracts.contract_versions import (
    COMPATIBILITY_MODES,
    CONTRACT_VERSIONS,
    DEFAULT_SESSION_ID,
    PROTOCOL_VERSION,
    SCHEMA_VERSION,
    TCP_PROTOCOL_VERSION,
    UART_PROTOCOL_VERSION,
    WEB_PROTOCOL_VERSION,
    WEB_PROTOCOL_VERSION_ALIAS,
    WEB_SCHEMA_VERSION,
    now_iso,
    resolve_compatibility_mode,
    validate_transport_proto_version,
)
from robot_contracts.envelope_contract import (
    BridgeEnvelope,
    CommandAck,
    EnvelopeValidationError,
    contract_version_snapshot,
    ensure_event_type,
    make_envelope,
    now_iso,
    validate_envelope_dict,
    validate_outbound_command_type,
)
from robot_contracts.runtime_parameters import (
    DEFAULT_RUNTIME_PARAM_CONSUMERS,
    RUNTIME_PARAM_ACK_MODE_ALL,
    RUNTIME_PARAM_ACK_MODE_BEST_EFFORT,
    RUNTIME_PARAM_PROFILES,
    RUNTIME_PARAM_SCHEMA,
    TRANSACTION_STATE_APPLIED,
    TRANSACTION_STATE_FAILED,
    TRANSACTION_STATE_PENDING,
    TRANSACTION_STATE_TIMEOUT,
    RuntimeParameterError,
    RuntimeParameterState,
    RuntimeParameterTransaction,
    apply_runtime_param_profile,
    apply_runtime_param_update,
    build_runtime_param_metadata,
    coerce_runtime_param_value,
    runtime_param_defaults,
    runtime_param_digest,
    runtime_param_profiles,
    validate_runtime_param_key,
)

__all__ = [
    'BRIDGE_CAPABILITIES',
    'COMMAND_ACK_STATUSES',
    'COMMAND_LIFECYCLE_STATUSES',
    'COMMAND_PERMISSION_MATRIX',
    'COMMAND_TARGET_MODE',
    'COMMAND_TYPES',
    'COMPATIBILITY_ACK_STATUS_BY_LIFECYCLE',
    'COMPATIBILITY_MODES',
    'CONTRACT_VERSIONS',
    'CommandAck',
    'CommandContext',
    'ContractCheckResult',
    'DEFAULT_SESSION_ID',
    'EnvelopeValidationError',
    'INBOUND_EVENT_TYPES',
    'MODE_TRANSITION_TARGETS',
    'PROTOCOL_VERSION',
    'DEFAULT_RUNTIME_PARAM_CONSUMERS',
    'RUNTIME_PARAM_ACK_MODE_ALL',
    'RUNTIME_PARAM_ACK_MODE_BEST_EFFORT',
    'RUNTIME_PARAM_PROFILES',
    'RUNTIME_PARAM_SCHEMA',
    'TRANSACTION_STATE_APPLIED',
    'TRANSACTION_STATE_FAILED',
    'TRANSACTION_STATE_PENDING',
    'TRANSACTION_STATE_TIMEOUT',
    'RuntimeParameterError',
    'RuntimeParameterState',
    'RuntimeParameterTransaction',
    'SCHEMA_VERSION',
    'TCP_PROTOCOL_VERSION',
    'TERMINAL_COMMAND_ACK_STATUSES',
    'TERMINAL_COMMAND_LIFECYCLE_STATUSES',
    'TRANSPORT_SUMMARY_KEYS',
    'UART_PROTOCOL_VERSION',
    'WEB_PROTOCOL_VERSION',
    'WEB_PROTOCOL_VERSION_ALIAS',
    'WEB_SCHEMA_VERSION',
    'BridgeEnvelope',
    'allowed_target_modes',
    'compatibility_ack_status',
    'apply_runtime_param_profile',
    'apply_runtime_param_update',
    'build_runtime_param_metadata',
    'coerce_runtime_param_value',
    'command_allowed_modes',
    'command_capability_snapshot',
    'command_guard',
    'contract_version_snapshot',
    'ensure_event_type',
    'make_envelope',
    'mode_transition_allowed',
    'now_iso',
    'resolve_compatibility_mode',
    'runtime_param_defaults',
    'runtime_param_digest',
    'runtime_param_profiles',
    'supported_capabilities',
    'validate_envelope_dict',
    'validate_outbound_command_type',
    'validate_runtime_param_key',
    'validate_transport_proto_version',
]
