[platformio]
default_envs = bluepill_f103c8
include_dir = include
src_dir = src

[env]
platform = ststm32
monitor_speed = 115200
build_flags =
    -std=gnu11
    -Iinclude
    -Wl,--specs=nano.specs
    -Wl,--specs=nosys.specs

[env:bluepill_f103c8]
board = bluepill_f103c8
framework = cmsis
debug_tool = stlink
upload_protocol = stlink

[env:bluepill_f103c8_stm32cube]
board = bluepill_f103c8
framework = stm32cube
debug_tool = stlink
upload_protocol = stlink

[env:native]
platform = native
build_flags =
    -std=gnu11
    -Iinclude
