[pytest]
testpaths = ros2_ws/src/robot_tests
norecursedirs =
    .git
    .github
    .pytest_cache
    __pycache__
    robot_frontend/node_modules
    robot_frontend/dist
addopts = --import-mode=importlib
