from __future__ import annotations

from robot_contracts.bridge_contract import TCP_PROTOCOL_VERSION

MODE_BOOT = 'BOOT'
MODE_IDLE = 'IDLE'
MODE_MANUAL = 'MANUAL'
MODE_PATROL = 'PATROL'
MODE_TRACK = 'TRACK'
MODE_SAFE_STOP = 'SAFE_STOP'
MODE_FAULT = 'FAULT'

ALL_MODES = {
    MODE_BOOT,
    MODE_IDLE,
    MODE_MANUAL,
    MODE_PATROL,
    MODE_TRACK,
    MODE_SAFE_STOP,
    MODE_FAULT,
}

MODE_PRIORITY = {
    MODE_FAULT: 100,
    MODE_SAFE_STOP: 90,
    MODE_MANUAL: 80,
    MODE_TRACK: 70,
    MODE_PATROL: 60,
    MODE_IDLE: 10,
    MODE_BOOT: 0,
}

CONTROL_SOURCE_IDLE = 'idle'
CONTROL_SOURCE_MANUAL = 'manual'
CONTROL_SOURCE_TRACK = 'track'
CONTROL_SOURCE_PATROL = 'patrol'
CONTROL_SOURCE_SAFETY = 'safety'
CONTROL_SOURCE_POWER = 'power_guard'
CONTROL_SOURCE_FAULT = 'fault_hold'

FAULT_LEVEL_INFO = 'info'
FAULT_LEVEL_WARN = 'warn'
FAULT_LEVEL_ERROR = 'error'
FAULT_LEVEL_FATAL = 'fatal'
FAULT_LEVELS = {FAULT_LEVEL_INFO, FAULT_LEVEL_WARN, FAULT_LEVEL_ERROR, FAULT_LEVEL_FATAL}

FAULT_LOW_BAT = 'LOW_BAT'
FAULT_LOW_BAT_WARN = 'LOW_BAT_WARN'
FAULT_LOW_BAT_CRITICAL = 'LOW_BAT_CRITICAL'
FAULT_LOW_BAT_STOP = 'LOW_BAT_STOP'
FAULT_COMM_LOSS = 'COMM_LOSS'
FAULT_ESTOP = 'ESTOP'
FAULT_MOTOR = 'MOTOR_FAULT'
FAULT_DRIVER = 'DRIVER_FAULT'
FAULT_LINK = 'LINK_FAULT'
FAULT_UART = 'UART_FAULT'
FAULT_CAMERA = 'CAMERA_FAULT'
FAULT_AUDIO = 'AUDIO_FAULT'
FAULT_VOICE = 'VOICE_FAULT'
FAULT_PROTOCOL = 'PROTOCOL_FAULT'
FAULT_ENCODER = 'ENCODER_FAULT'
FAULT_WATCHDOG = 'WATCHDOG_FAULT'
FAULT_CONFIG = 'CONFIG_MISMATCH'
FAULT_CODES = {
    FAULT_LOW_BAT,
    FAULT_LOW_BAT_WARN,
    FAULT_LOW_BAT_CRITICAL,
    FAULT_LOW_BAT_STOP,
    FAULT_COMM_LOSS,
    FAULT_ESTOP,
    FAULT_MOTOR,
    FAULT_DRIVER,
    FAULT_LINK,
    FAULT_UART,
    FAULT_CAMERA,
    FAULT_AUDIO,
    FAULT_VOICE,
    FAULT_PROTOCOL,
    FAULT_ENCODER,
    FAULT_WATCHDOG,
    FAULT_CONFIG,
}

POWER_LEVEL_NORMAL = 'normal'
POWER_LEVEL_WARN = 'warn'
POWER_LEVEL_LIMITED = 'limited'
POWER_LEVEL_STOP_REQUIRED = 'stop_required'
POWER_LEVELS = {POWER_LEVEL_NORMAL, POWER_LEVEL_WARN, POWER_LEVEL_LIMITED, POWER_LEVEL_STOP_REQUIRED}

VOICE_CMD_START_PATROL = 'start_patrol'
VOICE_CMD_STOP_PATROL = 'stop_patrol'
VOICE_CMD_FORWARD = 'forward'
VOICE_CMD_BACKWARD = 'backward'
VOICE_CMD_LEFT = 'left'
VOICE_CMD_RIGHT = 'right'
VOICE_CMD_STOP = 'stop'
VOICE_CMD_IDLE = 'idle'
VOICE_CMD_RESET_FAULT = 'reset_fault'
VOICE_CMD_MANUAL = 'manual'
VOICE_CMD_SNAPSHOT = 'snapshot'
VOICE_CMD_RESUME = 'resume_from_safe_stop'
VOICE_CMD_STATUS = 'status'

MODE_COMMANDS = {VOICE_CMD_START_PATROL, VOICE_CMD_STOP_PATROL, VOICE_CMD_IDLE, VOICE_CMD_MANUAL, VOICE_CMD_RESET_FAULT, VOICE_CMD_RESUME}
MOTION_COMMANDS = {VOICE_CMD_FORWARD, VOICE_CMD_BACKWARD, VOICE_CMD_LEFT, VOICE_CMD_RIGHT, VOICE_CMD_STOP}
VOICE_COMMANDS = MODE_COMMANDS | MOTION_COMMANDS | {VOICE_CMD_SNAPSHOT, VOICE_CMD_STATUS}
DANGEROUS_VOICE_COMMANDS = {VOICE_CMD_START_PATROL, VOICE_CMD_FORWARD, VOICE_CMD_BACKWARD, VOICE_CMD_LEFT, VOICE_CMD_RIGHT, VOICE_CMD_RESUME}

SPEAK_PRIORITY_INFO = 1
SPEAK_PRIORITY_WARN = 5
SPEAK_PRIORITY_FATAL = 9

VISION_TARGET_NONE = 'none'
VISION_TARGET_COLOR = 'color'
VISION_TARGET_QRCODE = 'qrcode'

EVENT_LEVEL_INFO = 'info'
EVENT_LEVEL_WARN = 'warn'
EVENT_LEVEL_ERROR = 'error'

HEALTH_GOOD = 'good'
HEALTH_DEGRADED = 'degraded'
HEALTH_FAULTED = 'faulted'

SNAPSHOT_REASON_QRCODE = 'qrcode'
SNAPSHOT_REASON_TARGET = 'target'
SNAPSHOT_REASON_FAULT = 'fault'
SNAPSHOT_REASON_VOICE = 'voice'
SNAPSHOT_REASON_TRACK = 'track'

PROTO_ACTION_ACCEPT = 'accept'
PROTO_ACTION_IGNORE = 'ignore'
PROTO_ACTION_WARN = 'warn'
PROTO_ACTION_FAULT = 'fault'
PROTO_ACTIONS = {PROTO_ACTION_ACCEPT, PROTO_ACTION_IGNORE, PROTO_ACTION_WARN, PROTO_ACTION_FAULT}

READINESS_READY = 'ready'
READINESS_DEGRADED = 'degraded'
READINESS_BLOCKED = 'blocked'
READINESS_BOOTING = 'booting'

FRAME_ODOM = 'odom'
FRAME_BASE_LINK = 'base_link'
FRAME_CAMERA = 'camera_link'
TOPIC_ODOM = '/odom'
TOPIC_BATTERY = '/battery_state'
TOPIC_BRIDGE_SUMMARY = '/robot/bridge/summary'
TOPIC_TRANSPORT_STATS = '/robot/bridge/transport_stats'
TOPIC_SYSTEM_STATUS = '/robot/system_status'
TOPIC_CHASSIS_STATE = '/robot/chassis_state'
TOPIC_POWER_STATE = '/robot/power_state'
TOPIC_FAULT = '/robot/fault'

PROTO_VER = TCP_PROTOCOL_VERSION
