#ifndef GATEWAY_RUNTIME_H
#define GATEWAY_RUNTIME_H
#include "gateway_types.h"

gateway_runtime_config_t gateway_runtime_load_default(void);
int gateway_runtime_config_is_valid(gateway_runtime_config_t config);
gateway_transport_policy_t gateway_runtime_transport_policy(gateway_runtime_config_t config);
gateway_transport_frame_t gateway_runtime_bootstrap_frame(gateway_transport_policy_t policy);
void gateway_runtime_print_boot_report(gateway_runtime_config_t config);

#endif
